from __future__ import annotations

import sys
from pathlib import Path
from typing import Any
from uuid import UUID

PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(
        0,
        str(PROJECT_ROOT),
    )


from database.repositories.analysis import (
    complete_analysis_run,
    create_analysis_run,
    create_incident,
    get_analysis_run,
    list_incidents,
    list_predictions,
    save_prediction_batch,
)
from database.repositories.models import (
    list_model_versions,
)
from database.repositories.telemetry import (
    list_telemetry_samples,
)
from database.repositories.telemetry_sessions import (
    list_telemetry_sessions,
)


def to_uuid(
    value: object,
) -> UUID:
    if isinstance(value, UUID):
        return value

    return UUID(str(value))


def find_opssat_session_id() -> UUID:
    """
    Return the latest OPS-SAT telemetry session.
    """

    sessions = list_telemetry_sessions()

    for session in sessions:
        if session.get("source_type") == "opssat":
            return to_uuid(
                session["id"]
            )

    raise RuntimeError(
        "No OPS-SAT telemetry session was found."
    )


def find_random_forest_model_id() -> UUID:
    """
    Return the registered supervised Random Forest model.
    """

    models = list_model_versions()

    for model in models:
        if (
            model.get("model_name")
            == "OPSSAT Supervised Random Forest"
            and model.get("version") == "1.0"
        ):
            return to_uuid(
                model["id"]
            )

    raise RuntimeError(
        "OPSSAT Supervised Random Forest version "
        "1.0 was not found."
    )


def select_test_samples(
    samples: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """
    Select normal and anomaly samples for a storage test.

    Ground-truth labels are used only to build deterministic
    database test records. This is not a model evaluation.
    """

    normal_samples = [
        sample
        for sample in samples
        if not bool(
            sample.get("ground_truth_label")
        )
    ]

    anomaly_samples = [
        sample
        for sample in samples
        if bool(
            sample.get("ground_truth_label")
        )
    ]

    if len(normal_samples) < 4:
        raise RuntimeError(
            "At least four normal samples are required."
        )

    if len(anomaly_samples) < 2:
        raise RuntimeError(
            "At least two anomaly samples are required."
        )

    return (
        normal_samples[:4]
        + anomaly_samples[:2]
    )


def build_test_predictions(
    samples: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """
    Build deterministic persistence-test predictions.

    These records test database storage only.
    """

    predictions: list[dict[str, Any]] = []

    for sample in samples:
        is_anomaly = bool(
            sample["ground_truth_label"]
        )

        sample_metadata = (
            sample.get("sample_metadata")
            or {}
        )

        channel = str(
            sample_metadata.get(
                "channel",
                "unknown",
            )
        )

        if is_anomaly:
            risk_level = "Critical"
            risk_score = 91.0
            confidence_score = 95.0
            top_feature = "var"
            affected_subsystems = [
                channel
            ]
            explanation = (
                "Synthetic persistence-test anomaly. "
                "Not generated by the production model."
            )

        else:
            risk_level = "Normal"
            risk_score = 8.0
            confidence_score = 93.0
            top_feature = "mean"
            affected_subsystems = []
            explanation = (
                "Synthetic persistence-test normal "
                "prediction. Not generated by the "
                "production model."
            )

        predictions.append(
            {
                "telemetry_sample_id": int(
                    sample["id"]
                ),
                "predicted_anomaly": is_anomaly,
                "risk_level": risk_level,
                "risk_score": risk_score,
                "confidence_score": (
                    confidence_score
                ),
                "isolation_score": (
                    88.0 if is_anomaly else 10.0
                ),
                "forecast_residual_score": None,
                "rule_score": (
                    75.0 if is_anomaly else 5.0
                ),
                "persistence_score": (
                    70.0 if is_anomaly else 4.0
                ),
                "early_warning_score": (
                    84.0 if is_anomaly else 7.0
                ),
                "top_feature": top_feature,
                "out_of_distribution": False,
                "human_review_required": (
                    is_anomaly
                ),
                "explanation": explanation,
                "feature_contributions": {
                    "var": (
                        0.74 if is_anomaly else 0.08
                    ),
                    "mean": (
                        0.18 if is_anomaly else 0.05
                    ),
                },
                "rule_violations": (
                    [
                        {
                            "rule": (
                                "storage_test_rule"
                            ),
                            "severity": "Critical",
                        }
                    ]
                    if is_anomaly
                    else []
                ),
                "affected_subsystems": (
                    affected_subsystems
                ),
                "prediction_metadata": {
                    "storage_test": True,
                    "production_prediction": False,
                    "source": (
                        "test_analysis_storage.py"
                    ),
                },
            }
        )

    return predictions


def main() -> None:
    print("=" * 76)
    print("MissionGuard Analysis Storage Test")
    print("=" * 76)

    print(
        "\n1. Finding OPS-SAT telemetry session..."
    )

    telemetry_session_id = (
        find_opssat_session_id()
    )

    print(
        f"Telemetry session ID: "
        f"{telemetry_session_id}"
    )

    print(
        "\n2. Finding Random Forest model..."
    )

    model_version_id = (
        find_random_forest_model_id()
    )

    print(
        f"Model version ID: "
        f"{model_version_id}"
    )

    print(
        "\n3. Reading telemetry samples..."
    )

    all_samples = list_telemetry_samples(
        telemetry_session_id
    )

    print(
        f"Available samples: "
        f"{len(all_samples)}"
    )

    test_samples = select_test_samples(
        all_samples
    )

    print(
        f"Selected test samples: "
        f"{len(test_samples)}"
    )

    print(
        "\n4. Creating analysis run..."
    )

    analysis_run_id = create_analysis_run(
        session_id=telemetry_session_id,
        model_version_id=model_version_id,
        run_type="other",
        status="running",
        metadata={
            "storage_test": True,
            "production_run": False,
            "description": (
                "Database persistence test using "
                "deterministic sample predictions."
            ),
        },
    )

    print(
        f"Analysis run ID: "
        f"{analysis_run_id}"
    )

    print(
        "\n5. Saving predictions..."
    )

    prediction_records = build_test_predictions(
        test_samples
    )

    prediction_result = save_prediction_batch(
        analysis_run_id=analysis_run_id,
        prediction_records=prediction_records,
    )

    print(
        f"Stored predictions: "
        f"{prediction_result.stored_predictions}"
    )

    print(
        f"Anomaly predictions: "
        f"{prediction_result.anomaly_predictions}"
    )

    anomalous_samples = [
        sample
        for sample in test_samples
        if bool(
            sample["ground_truth_label"]
        )
    ]

    first_anomaly = anomalous_samples[0]

    sample_metadata = (
        first_anomaly.get("sample_metadata")
        or {}
    )

    channel = str(
        sample_metadata.get(
            "channel",
            "unknown",
        )
    )

    print(
        "\n6. Creating test incident..."
    )

    incident_id = create_incident(
        analysis_run_id=analysis_run_id,
        incident_code="STORAGE-TEST-001",
        start_sample_id=int(
            first_anomaly["id"]
        ),
        end_sample_id=int(
            first_anomaly["id"]
        ),
        started_at=first_anomaly.get(
            "timestamp"
        ),
        ended_at=first_anomaly.get(
            "timestamp"
        ),
        duration_samples=1,
        severity="Critical",
        peak_risk_score=91.0,
        peak_confidence=95.0,
        top_feature="var",
        affected_subsystems=[
            channel
        ],
        human_review_required=True,
        status="open",
        summary=(
            "Synthetic incident created to verify "
            "MissionGuard database persistence."
        ),
        metadata={
            "storage_test": True,
            "production_incident": False,
        },
    )

    print(
        f"Incident ID: "
        f"{incident_id}"
    )

    print(
        "\n7. Completing analysis run..."
    )

    complete_analysis_run(
        analysis_run_id=analysis_run_id,
        total_predictions=(
            prediction_result.stored_predictions
        ),
        total_anomalies=(
            prediction_result.anomaly_predictions
        ),
        total_incidents=1,
        mission_health_score=None,
        metadata={
            "storage_test": True,
            "production_run": False,
            "completed_successfully": True,
        },
    )

    stored_run = get_analysis_run(
        analysis_run_id
    )

    if stored_run is None:
        raise RuntimeError(
            "Analysis run could not be found."
        )

    stored_predictions = list_predictions(
        analysis_run_id
    )

    stored_incidents = list_incidents(
        analysis_run_id
    )

    print(
        "\n8. Stored analysis summary"
    )

    print(
        f"Run status: "
        f"{stored_run['status']}"
    )

    print(
        f"Total predictions: "
        f"{stored_run['total_predictions']}"
    )

    print(
        f"Total anomalies: "
        f"{stored_run['total_anomalies']}"
    )

    print(
        f"Total incidents: "
        f"{stored_run['total_incidents']}"
    )

    print(
        f"Predictions read back: "
        f"{len(stored_predictions)}"
    )

    print(
        f"Incidents read back: "
        f"{len(stored_incidents)}"
    )

    if stored_run["status"] != "completed":
        raise RuntimeError(
            "Analysis run was not completed."
        )

    if len(stored_predictions) != 6:
        raise RuntimeError(
            "Expected 6 stored predictions."
        )

    if len(stored_incidents) != 1:
        raise RuntimeError(
            "Expected one stored incident."
        )

    print(
        "\nAnalysis storage test "
        "completed successfully."
    )


if __name__ == "__main__":
    main()